### ISSUE TITLE
[Feature Request] Add a way to change the status colors.

### ISSUE THREAD

**Issue by joered05** [vrcx-team/VRCX#468]
Hi! I occasionally have a hard time telling similar colors apart. For the most part, this doesn't cause any issues with VRCX, except with the status icons. Personally, due to the colors being similar I have a hard time telling the difference between the orange 'Ask Me' and the red 'Do Not Disturb.'

Would it be possible to add an option to customize the status colors? If not, would it be possible to add a small icon to Do Not Disturb, similar to how Discord does it?

I've attached a little example image of what I would change the colors to. On the left is the current colors for Do Not Disturb and Ask Me, on the right is what I personally would change it to. An option to change the colors would be greatly appreciated and help identify statuses easier.

![VRCXStatus](https://user-images.githubusercontent.com/38791254/213869711-4bbcd7e7-b928-4a75-b71f-46bdd4af1eb9.png)

**Comment by Natsumi-sama** [comment]
I've adjusted the default colours slightly here 
![](https://user-images.githubusercontent.com/11171153/213909723-e5e5cb66-0061-4577-9054-c0a5ddc26d28.png)

If you'd like to manually change the colours you can do so with a theme by creating/editing `%AppData%\VRCX\custom.css` and entering in your desired colours
```css
i.x-user-status.active {
    background: #f4e05e;
}
i.x-user-status.online {
    background: #67c23a;
}
i.x-user-status.joinme {
    background: #409eff;
}
i.x-user-status.askme {
    background: #ff9500;
}
i.x-user-status.busy {
    background: #ff2c2c;
}
```
